name: CI
on:
    push:
    workflow_dispatch:

jobs:
    check_database:
        name: Check database
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: stable

            - uses: actions/checkout@v4
              with:
                ref: testing

            - uses: actions/checkout@v4
          
            - name: Checkout branches
              run: |
                git checkout stable
                git checkout testing
                git checkout $GITHUB_REF

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - run: npm ci

            - name: Get Date
              id: get-date
              run: |
                echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

            - name: Restore cached mod archives
              uses: actions/cache/restore@v4
              with:
                path: |
                  build/cache
                key: mod-cache-${{ steps.get-date.outputs.date }}
                restore-keys: |
                  mod-cache-

            - name: Test the stable branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: BRANCH=stable npm run test

            - name: Test the testing branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: BRANCH=testing npm run test

            - name: Save mod archive cache
              uses: actions/cache/save@v4
              with:
                path: |
                  build/cache
                key: mod-cache-${{ steps.get-date.outputs.date }}
