name: CI
on:
    push:
    workflow_dispatch:

jobs:
    check_database:
        name: Check database
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: stable

            - uses: actions/checkout@v4
              with:
                ref: testing

            - uses: actions/checkout@v4
          
            - name: Checkout branches
              run: |
                git checkout stable
                git checkout testing
                git checkout $GITHUB_REF

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - run: npm ci
            
            - name: Test the stable branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: BRANCH=stable npm run test

            - name: Test the testing branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: BRANCH=testing npm run test

